apiVersion: apps/v1
kind: Deployment
metadata:
  name: habits-api
  namespace: habits-app
  labels:
    app: habits-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: habits-api
  template:
    metadata:
      labels:
        app: habits-api
    spec:
      containers:
      - name: habits-api
        image: YOUR_ECR_REPO/habits-api:latest  # Replace with your ECR repository
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: habits-api-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: habits-api-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: habits-api-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: habits-api-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: habits-api-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: habits-api-secrets
              key: DB_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: habits-api-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: habits-api-service
  namespace: habits-app
spec:
  selector:
    app: habits-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer  # Creates an AWS ELB
