apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - secret.yaml
  - cronjob.yaml

commonLabels:
  app: habit-notification
  component: cronjob
