apiVersion: v1
kind: Secret
metadata:
  name: mysql-ca
  namespace: habit-cron
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    YOUR_MYSQL_CA_CERT_PEM_CONTENT_HERE
    -----END CERTIFICATE-----
