apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: habit-notifier-netpol
  namespace: habit-tracker
  labels:
    app: habit-notifier
spec:
  podSelector:
    matchLabels:
      app: habit-notifier
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow connection to MySQL database
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 3306
  # Allow HTTPS for Twilio API
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
