apiVersion: v1
kind: ServiceAccount
metadata:
  name: habit-notifier-sa
  namespace: habit-tracker
  labels:
    app: habit-notifier
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: habit-notifier-role
  namespace: habit-tracker
  labels:
    app: habit-notifier
rules:
  # Allow reading ConfigMaps and Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  # Allow reading own pod information for logging/debugging
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: habit-notifier-rolebinding
  namespace: habit-tracker
  labels:
    app: habit-notifier
subjects:
  - kind: ServiceAccount
    name: habit-notifier-sa
    namespace: habit-tracker
roleRef:
  kind: Role
  name: habit-notifier-role
  apiGroup: rbac.authorization.k8s.io
