apiVersion: batch/v1
kind: CronJob
metadata:
  name: habit-notifier
  namespace: default
  labels:
    app: habit-notifier
    component: notification
spec:
  # Run every day at 8:00 AM UTC
  # Format: minute hour day-of-month month day-of-week
  schedule: "0 8 * * *"
  
  # Timezone (requires Kubernetes 1.25+)
  timeZone: "UTC"
  
  # Concurrency policy
  # Forbid: Don't start a new job if previous one is still running
  concurrencyPolicy: Forbid
  
  # Number of successful finished jobs to retain
  successfulJobsHistoryLimit: 3
  
  # Number of failed finished jobs to retain
  failedJobsHistoryLimit: 3
  
  # Deadline in seconds for starting the job if it misses scheduled time
  startingDeadlineSeconds: 300
  
  jobTemplate:
    metadata:
      labels:
        app: habit-notifier
        component: notification
    spec:
      # Time to retain completed job pods
      ttlSecondsAfterFinished: 86400  # 24 hours
      
      # Number of retries before marking job as failed
      backoffLimit: 3
      
      # Maximum time for the job to complete
      activeDeadlineSeconds: 600  # 10 minutes
      
      template:
        metadata:
          labels:
            app: habit-notifier
            component: notification
          annotations:
            # Prometheus annotations for monitoring
            prometheus.io/scrape: "false"
        spec:
          serviceAccountName: habit-notifier-sa
          
          # Security context for the pod
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          
          # Restart policy for the job
          restartPolicy: OnFailure
          
          containers:
          - name: notifier
            # Replace with your actual image
            image: your-registry/habit-notifier:latest
            imagePullPolicy: Always
            
            # Security context for the container
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
            
            # Environment variables from ConfigMap
            envFrom:
            - configMapRef:
                name: habit-notifier-config
            
            # Environment variables from Secret
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: habit-notifier-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: habit-notifier-secret
                  key: DB_PASSWORD
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: habit-notifier-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: habit-notifier-secret
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_FROM_NUMBER
              valueFrom:
                secretKeyRef:
                  name: habit-notifier-secret
                  key: TWILIO_FROM_NUMBER
            
            # Resource limits and requests
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "500m"
            
            # Liveness probe (checks if container is alive)
            livenessProbe:
              exec:
                command:
                - sh
                - -c
                - "ps aux | grep habit-notifier | grep -v grep"
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            
            # Startup probe (gives container time to start)
            startupProbe:
              exec:
                command:
                - sh
                - -c
                - "ps aux | grep habit-notifier | grep -v grep"
              initialDelaySeconds: 0
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 30
          
          # Image pull secrets (if using private registry)
          # imagePullSecrets:
          # - name: registry-credentials
          
          # Node selector for scheduling
          # nodeSelector:
          #   workload: batch
          
          # Tolerations for taints
          # tolerations:
          # - key: "batch"
          #   operator: "Equal"
          #   value: "true"
          #   effect: "NoSchedule"
          
          # Affinity rules
          # affinity:
          #   nodeAffinity:
          #     preferredDuringSchedulingIgnoredDuringExecution:
          #     - weight: 1
          #       preference:
          #         matchExpressions:
          #         - key: workload
          #           operator: In
          #           values:
          #           - batch

