apiVersion: batch/v1
kind: CronJob
metadata:
  name: habit-tracker-cronjob
  labels:
    app: habit-tracker
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: habit-tracker
            image: your-docker-repo/habit-tracker:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: habit-tracker-config
            - secretRef:
                name: habit-tracker-secrets
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure
