apiVersion: v1
kind: Secret
metadata:
  name: habit-reminder-secrets
type: Opaque
data:
  # Base64 encoded secrets
  DB_USER: "" # echo -n 'your-db-user' | base64
  DB_PASSWORD: "" # echo -n 'your-db-password' | base64
  DB_HOST: "" # echo -n 'your-db-host' | base64
  DB_NAME: "" # echo -n 'your-db-name' | base64
  TWILIO_ACCOUNT_SID: "" # echo -n 'your-twilio-account-sid' | base64
  TWILIO_AUTH_TOKEN: "" # echo -n 'your-twilio-auth-token' | base64
  TWILIO_PHONE_NUMBER: "" # echo -n 'your-twilio-phone-number' | base64
