apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

# Base resources
resources:
  - ../../

# Production-specific labels
commonLabels:
  environment: production

# Production image tag
images:
  - name: your-registry/habit-notifier
    newName: your-registry/habit-notifier
    newTag: v1.0.0

# Patches for production
patches:
  - target:
      kind: CronJob
      name: habit-notifier
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "0 8 * * *"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

